# Generated by Django 4.2.7 on 2026-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_fix_last_search_date_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchconfiguration',
            name='prompts',
            field=models.JSONField(blank=True, default=dict, help_text='Все промпты: system_prompts, search_prompts, manufacturer_prompts. Пустой {} = дефолтные промпты.', verbose_name='Prompts'),
        ),
    ]
